services:
  vault-injector:
    build: .
    container_name: vault-injector
    restart: always
    env_file:
      - .env
    volumes:
      - /home/gmadmin/unicorn-wallet:/home/gmadmin/unicorn-wallet
      - /home/gmadmin/unicorn-backend:/home/gmadmin/unicorn-backend
